# Generated by Django 4.2.30 on 2026-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Bridal, Arabic, Party, Crafts', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Short name used for filtering (e.g. bridal, arabic, party, crafts)', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='mehndidesign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='designs', to='bookings.category'),
        ),
    ]
