# Generated by Django 4.2.30 on 2026-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_category_mehndidesign_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='booking_attachments/'),
        ),
    ]
