# Generated by Django 4.2.30 on 2026-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookinginquiry_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehndidesign',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
