# Generated by Django 4.2.30 on 2026-07-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_mehndidesign_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon identifier (e.g. 💍, 🎉, 🌿, 🎨)', max_length=50, null=True)),
                ('price', models.CharField(help_text='e.g. ₹2,500+ or ₹250/person', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 10-12 hrs or 1-2 hrs/person', max_length=50)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of feature bullet points')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['order', 'id'],
            },
        ),
    ]
