# Generated by Django 4.2.30 on 2026-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_servicepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_file', models.FileField(blank=True, help_text='Direct MP4 Upload', null=True, upload_to='reels/videos/')),
                ('external_url', models.URLField(blank=True, help_text='YouTube Shorts / Instagram Reel link', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reels/thumbnails/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reel / Video',
                'verbose_name_plural': 'Reels / Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
