# Generated by Django 4.2.30 on 2026-07-29 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='reels/videos/'),
            preserve_default=False,
        ),
    ]
