# Generated by Django 4.2.30 on 2026-07-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_reel_external_url_alter_reel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='bookings.mehndidesign')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='bookings.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visitor_id'], name='idx_visitor_id'),
        ),
        migrations.AddField(
            model_name='reellike',
            name='reel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bookings.reel'),
        ),
        migrations.AddField(
            model_name='reellike',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to='bookings.visitor'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('visitor', 'design')},
        ),
        migrations.AlterUniqueTogether(
            name='reellike',
            unique_together={('visitor', 'reel')},
        ),
    ]
