# Generated by Django 4.2.30 on 2026-07-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_reellike_visitor_wishlist_visitor_idx_visitor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookings.reel')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comments', to='bookings.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
