# Generated by Django 4.2.30 on 2026-07-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_reelcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookings.reel')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_bookmarks', to='bookings.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('visitor', 'reel')},
            },
        ),
    ]
